DROP SCHEMA IF EXISTS SICPAG;
CREATE SCHEMA SICPAG DEFAULT CHARACTER SET utf8mb4;
USE SICPAG;

CREATE TABLE TIPOSECAO (
	ID INT NOT NULL AUTO_INCREMENT,
	TIPO VARCHAR(64) NOT NULL,
	ORDEM INT NOT NULL,
	CONSTRAINT PK_ID PRIMARY KEY (ID),
	CONSTRAINT UQ_TIPO UNIQUE (TIPO),
	CONSTRAINT UQ_ORDEM UNIQUE (ORDEM)
) ENGINE=InnoDB;

CREATE TABLE SECAO (
	ID INT NOT NULL AUTO_INCREMENT,
	SIGLA VARCHAR(16) NOT NULL,
	ID_PAI INT DEFAULT NULL,
	ID_TIPO INT NOT NULL,
	CONSTRAINT PK_ID PRIMARY KEY (ID),
	CONSTRAINT UQ_SIGLA UNIQUE (SIGLA, ID_PAI),
	CONSTRAINT FK_SECAO_PAI FOREIGN KEY (ID_PAI) REFERENCES SECAO(ID),
	CONSTRAINT FK_SECAO_TIPO FOREIGN KEY (ID_TIPO) REFERENCES TIPOSECAO(ID)
) ENGINE=InnoDB;

CREATE TABLE USUARIO (
	ID INT NOT NULL AUTO_INCREMENT,
	LOGIN CHAR(11) NOT NULL,
	NOME VARCHAR(128) DEFAULT '',
	ID_SECAO INT DEFAULT NULL,
	DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT PK_ID PRIMARY KEY (ID),
	CONSTRAINT UQ_LOGIN UNIQUE (LOGIN),
	CONSTRAINT FK_USUARIO_SECAO FOREIGN KEY (ID_SECAO) REFERENCES SECAO(ID)
) ENGINE=InnoDB;

CREATE TABLE SENHATEMPORARIA (
	ID INT NOT NULL AUTO_INCREMENT,
	SENHA CHAR(12) NOT NULL,
	DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ID_USUARIO INT NOT NULL,
	CONSTRAINT PK_ID PRIMARY KEY (ID),
	CONSTRAINT UQ_SENHA UNIQUE (SENHA),
	CONSTRAINT FK_SENHATEMPORARIA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE PERFIL (
	ID INT NOT NULL AUTO_INCREMENT,
	PERFIL CHAR(2) NOT NULL,
	NOME VARCHAR(128) NOT NULL,
	CONSTRAINT PK_ID PRIMARY KEY (ID),
	CONSTRAINT UQ_PERFIL UNIQUE (PERFIL)
) ENGINE=InnoDB;

CREATE TABLE USUARIO_PERFIL (
	ID INT NOT NULL AUTO_INCREMENT,
	ID_USUARIO INT NOT NULL,
	ID_PERFIL INT NOT NULL,
	CONSTRAINT PK_ID PRIMARY KEY (ID),
	CONSTRAINT UQ_USUARIO_PERFIL UNIQUE (ID_USUARIO, ID_PERFIL),
	CONSTRAINT FK_USUARIO_PERFIL_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE,
	CONSTRAINT FK_USUARIO_PERFIL_PERFIL FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL(ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE MODALIDADE (
	ID INT NOT NULL AUTO_INCREMENT,
	TIPO VARCHAR(64) NOT NULL,
	CONSTRAINT PK_ID PRIMARY KEY (ID),
	CONSTRAINT UQ_TIPO UNIQUE (TIPO)
) ENGINE=InnoDB;

CREATE TABLE DOCUMENTO (
	ID INT NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR(256) NOT NULL,
	ID_MODALIDADE INT NOT NULL,
	ID_USUARIO INT NOT NULL,
	CONSTRAINT PK_ID PRIMARY KEY (ID),
	CONSTRAINT FK_DOCUMENTO_MODALIDADE FOREIGN KEY (ID_MODALIDADE) REFERENCES MODALIDADE(ID),
	CONSTRAINT FK_DOCUMENTO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
) ENGINE=InnoDB;

CREATE TABLE PAG (
	ID INT NOT NULL AUTO_INCREMENT,
	NUMERO CHAR(20) NOT NULL,
	PAM VARCHAR(24) DEFAULT '',
	VOLUME VARCHAR(16) NOT NULL,
	SECAO VARCHAR(16) NOT NULL,
	ID_DOCUMENTO INT NOT NULL,
	CONSTRAINT PK_ID PRIMARY KEY (ID),
	CONSTRAINT UQ_NUMERO_VOLUME UNIQUE (NUMERO, VOLUME),
	CONSTRAINT FK_PAG_DOCUMENTO FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO(ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE TIPODERIVATIVO (
	ID INT NOT NULL AUTO_INCREMENT,
	TIPO VARCHAR(64) NOT NULL,
	CONSTRAINT PK_ID PRIMARY KEY (ID),
	CONSTRAINT UQ_TIPO UNIQUE (TIPO)
) ENGINE=InnoDB;

CREATE TABLE DERIVATIVO (
	ID INT NOT NULL AUTO_INCREMENT,
	CONTAGEM INT NOT NULL,
	PPM VARCHAR(24) DEFAULT '',
	VOLUME VARCHAR(16) NOT NULL,
	ID_DOCUMENTO INT NOT NULL,
	ID_PAG INT NOT NULL,
	ID_TIPODERIVATIVO INT NOT NULL,
	CONSTRAINT PK_ID PRIMARY KEY (ID),
	CONSTRAINT UQ_DERIVATIVO UNIQUE (CONTAGEM, ID_PAG, VOLUME),
	CONSTRAINT FK_DERIVATIVO_DOCUMENTO FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO(ID) ON DELETE CASCADE,
	CONSTRAINT FK_DERIVATIVO_PAG FOREIGN KEY (ID_PAG) REFERENCES PAG(ID),
	CONSTRAINT FK_DERIVATIVO_TIPODERIVATIVO FOREIGN KEY (ID_TIPODERIVATIVO) REFERENCES TIPODERIVATIVO(ID)
) ENGINE=InnoDB;

CREATE TABLE TIPORASTREIO (
	ID INT NOT NULL,
	TIPO VARCHAR(16) NOT NULL,
	CONSTRAINT PK_ID PRIMARY KEY (ID),
	CONSTRAINT UQ_TIPO UNIQUE (TIPO)
) ENGINE=InnoDB;	

CREATE TABLE RASTREIO (
	ID INT NOT NULL AUTO_INCREMENT,
	OBSERVACAO VARCHAR(512) NOT NULL DEFAULT 'Inclusão no sistema',
	DATA_MOVIMENTACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ID_DOCUMENTO INT NOT NULL,
	ID_SECAO INT NOT NULL,
	ID_USUARIO INT NOT NULL,
	ID_TIPO INT NOT NULL,
	CONSTRAINT PK_ID PRIMARY KEY (ID),
	CONSTRAINT FK_RASTREIO_DOCUMENTO FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO(ID) ON DELETE CASCADE,
	CONSTRAINT FK_RASTREIO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	CONSTRAINT FK_RASTREIO_SECAO FOREIGN KEY (ID_SECAO) REFERENCES SECAO(ID),
	CONSTRAINT FK_RASTREIO_TIPO FOREIGN KEY (ID_TIPO) REFERENCES TIPORASTREIO(ID)
) ENGINE=InnoDB;

INSERT INTO TIPOSECAO (TIPO, ORDEM) VALUES ('Unidade', 1), ('Divisão', 2), ('Subdivisão', 3), ('Setor', 4), ('Seção', 5), ('Subseção', 6);

INSERT INTO TIPORASTREIO (ID, TIPO) VALUES (1, 'Inclusão'), (2, 'Envio'), (3, 'Recebimento');

INSERT INTO PERFIL (PERFIL, NOME) VALUES
	('UD', 'Desenvolvedor do sistema'),
	('UA', 'Administrador do sistema'),
	('UM', 'Moderador do sistema'),
	('UN', 'Usuário do sistema'),
	('UB', 'Usuário bloqueado'),
	('AG', 'Gerenciador de documentos'),
	('AE', 'Editor de documentos'),
	('AT', 'Transferidor de documentos'),
	('CA', 'Consultor de relatórios'),
	('CR', 'Consultor de rastreios');

INSERT INTO MODALIDADE (TIPO) VALUES
	('Concorrência'),
	('Convite'),
	('Credenciamento'),
	('Dispensa'),
	('Inexigibilidade'),
	('Leilão'),
	('Não se Aplica'),
	('Pregão'),
	('Suprimento de Fundo'),
	('Sem Modalidade'),
	('Tomada de Preço'),
	('Transporte/Ressarcimento');
	
INSERT INTO TIPODERIVATIVO (TIPO) VALUES
	('PPM'), 
	('Credenciamento'), 
	('Reforço de Contrato');

INSERT INTO SECAO (SIGLA, ID_PAI, ID_TIPO) VALUES
	('UNIDADE', NULL, 1),
	('DIVISAO', 1, 2),
	('SECAO', 2, 5),
	('SUBSECAO', 3, 6); -- Seção do administrador

INSERT INTO USUARIO (LOGIN, ID_SECAO) VALUES ('11111111111', 4); -- CPF do administrador 
INSERT INTO USUARIO_PERFIL (ID_USUARIO, ID_PERFIL) VALUES (1, 1);